# Generated by Django 6.0.3 on 2026-03-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('year_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('FTSY', 'Fantasy'), ('SCIFI', 'Science Fiction'), ('MYST_THRILL', 'Mystery/Thriller'), ('ROM', 'Romance'), ('HIST_FIC', 'Historical Fiction'), ('HORROR', 'Horror'), ('DYST', 'Dystopian'), ('ADVN', 'Adventure'), ('BIO_AUTOBIO', 'Biography/Autobiography'), ('SELF_HELP', 'Self Help'), ('HIST', 'History'), ('SCI', 'Science'), ('BSNS', 'Business')], default='FTSY', max_length=11)),
                ('publication_date', models.DateField()),
                ('isbn', models.CharField()),
                ('number_of_pages', models.IntegerField()),
                ('cover_image', models.ImageField(upload_to='book_cover_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='reviews.author')),
            ],
        ),
    ]
